name: Deploy Spring

on: 
  workflow_dispatch:

jobs: 
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./gestion-proyectos
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      
      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml

      - name: Status
        run: ls -la target

      - name: Push to server
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "gestion-proyectos/target/gestion-proyectos-0.0.1-SNAPSHOT.jar"
          TARGET: "/var/www/ceu/server"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
      
